apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
spec:
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - name: demoapp
        image: docker.io/striver121/demoapp:latest
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
