apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  template:
    spec:
      containers:
      - name: demo-app
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets"
          readOnly: true
        - name: certificate-store
          mountPath: "/mnt/certificate"
          readOnly: true    
    volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "gcp-secretstore-connect"
      - name: certificate-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "gcp-certificatestore-connect" 
#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: demo-app
#spec:
#  selector:
#  template:
#    spec:
#      containers:
#      - name: mongodb
#        volumeMounts:
#        - mountPath: /data/db
#          name: data
#        - $patch: replace
