---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-certificatestore-connect
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/354967781493/secrets/app_certificate/versions/latest"
        path: "certificate.file"
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: gcp-secretstore-connect
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/354967781493/secrets/app_frontend/versions/latest"
        path: "frontend.secret"
      - resourceName: "projects/354967781493/secrets/app_middleware/versions/latest"
        path: "middleware.secret"
      - resourceName: "projects/354967781493/secrets/app_backend/versions/latest"
        path: "backend.secret"
