apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app
nameSuffix: -prd

resources:
  - ../../bases
      
images:
 - name: docker.io/striver121/demoapp:latest
   newName: docker.io/striver121/demoapp
   newTag: v.0.23
