---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-connect
spec:
  provider: vault
  parameters:
    vaultAddress: "http://10.44.13.233:8200"
    roleName: "mysecret"
    objects: |
      - objectName: "my-password"
        secretPath: "secret/data/my-pass"
        secretKey: "password"
#  secretObjects:
#  - secretName: vault-fetched-secret
#    type: Opaque
#    data:
#    - objectName: my-password
#      key: password
