apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-app
namesuffix: -dev

resources:
  - ../../base
  - resources/gcp-connect-sa.yaml
  - resources/secretproviderclass.yaml

patchesStrategicMerge:
  - resources/secret-insert-deployment.yaml
      
images:
 - name: docker.io/striver121/demoapp:latest
   newName: docker.io/striver121/demoapp
   newTag: v.0.23

#patchesJson6902:
#- target:
#    group: ""
#    version: v1
#    kind: ServiceAccount
#    name: gcp-connect-sa
#  patch: |-
#    - op: replace
#      path: /metadata/name
#      value: gcp-connect-sa   
